[package]
name = "holistic-threads"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "sums"
harness = false
